-- 052_smi_d6_remap_and_secure_firewall.sql
--
-- Two changes, applied editor-first; this is the versioned record.
--
-- (1) SM-I D6 remap. SM-I carried a 6th domain "The Scrum Master with
--     AI-Augmented Teams" (D6) at weight 0.00 — AI was authored but OUT of exam
--     scope, ghettoized in its own domain/module. This re-homes the 7 AI tasks
--     into D1–D5 where the work belongs (the SPO-I "AI woven through every
--     domain" model), re-homes their 6 lessons into Modules 1/2/4/5, flips 6 of
--     the 7 tasks to is_exam_scope=true (all but the one with no secure pool),
--     and retires the empty D6 domain + Module 6. Net: 5 domains, 5 modules, an
--     AI exam task in every domain. No domain weights change (D6 was 0).
--
--     Task re-map (codes renumbered to fit new homes; questions key off task
--     UUID, not code, so renumbering is safe):
--       6.4 -> D1 1.7   (exam)   empiricism under AI acceleration
--       6.1 -> D2 2.10  (exam)   AI agents as tools; human accountabilities
--       6.5 -> D2 2.11  (exam)   delegable AI work vs retained accountabilities
--       6.6 -> D3 3.11  (exam)   AI signal as input to inspection
--       6.2 -> D4 4.11  (exam)   DoD + transparency for AI-generated work
--       6.3 -> D5 5.10  (exam)   new impediments in AI-augmented teams
--       6.7 -> D5 5.11  (NOT exam — no secure pool yet; fast-follow secure-gen)
--
-- (2) Secure firewall cleanup. The SM-I secure pool (1,077 question_concepts
--     links across D1–D5, all langs) was generated by a legacy pre-firewall
--     path that wrote question_concepts like practice items do. That makes
--     secure exam questions reachable from practice via fetchConceptPractice —
--     a leak. SPO-I (built with the hardened task-first generator) was clean (0
--     links), confirming this is SM-I-only legacy residue. We delete every
--     question_concepts row belonging to an SM-I secure question. Practice
--     links (pool='practice') are untouched. The old generator path is retired;
--     the hardened generator (SPO-I's) never writes question_concepts for
--     secure items.
--
-- Idempotent: each statement is guarded so a re-run is a no-op once applied.

-- ---------------------------------------------------------------------------
-- (1a) Re-home the 7 AI tasks: reassign domain_id, renumber code, set exam-scope
-- ---------------------------------------------------------------------------

update public.tasks set
  domain_id = (select id from public.domains where certification_id='11111111-1111-1111-1111-111111111111' and code='D1'),
  code='1.7', order_index=7, is_exam_scope=true
where certification_id='11111111-1111-1111-1111-111111111111' and code='6.4';

update public.tasks set
  domain_id = (select id from public.domains where certification_id='11111111-1111-1111-1111-111111111111' and code='D2'),
  code='2.10', order_index=10, is_exam_scope=true
where certification_id='11111111-1111-1111-1111-111111111111' and code='6.1';

update public.tasks set
  domain_id = (select id from public.domains where certification_id='11111111-1111-1111-1111-111111111111' and code='D2'),
  code='2.11', order_index=11, is_exam_scope=true
where certification_id='11111111-1111-1111-1111-111111111111' and code='6.5';

update public.tasks set
  domain_id = (select id from public.domains where certification_id='11111111-1111-1111-1111-111111111111' and code='D3'),
  code='3.11', order_index=11, is_exam_scope=true
where certification_id='11111111-1111-1111-1111-111111111111' and code='6.6';

update public.tasks set
  domain_id = (select id from public.domains where certification_id='11111111-1111-1111-1111-111111111111' and code='D4'),
  code='4.11', order_index=11, is_exam_scope=true
where certification_id='11111111-1111-1111-1111-111111111111' and code='6.2';

update public.tasks set
  domain_id = (select id from public.domains where certification_id='11111111-1111-1111-1111-111111111111' and code='D5'),
  code='5.10', order_index=10, is_exam_scope=true
where certification_id='11111111-1111-1111-1111-111111111111' and code='6.3';

update public.tasks set
  domain_id = (select id from public.domains where certification_id='11111111-1111-1111-1111-111111111111' and code='D5'),
  code='5.11', order_index=11, is_exam_scope=false
where certification_id='11111111-1111-1111-1111-111111111111' and code='6.7';

-- ---------------------------------------------------------------------------
-- (1b) Re-home the 6 AI lesson groups (all languages) into Modules 1/2/4/5,
--      appended to the end of each target module's lesson order.
-- ---------------------------------------------------------------------------

-- a604 Empiricism Under Acceleration -> M1 (D1)
update public.lessons set
  module_id='a1111111-0000-0000-0000-000000000001',
  order_index=(select coalesce(max(order_index),0)+1 from public.lessons where module_id='a1111111-0000-0000-0000-000000000001')
where lesson_group_id='c0000000-0000-0000-0000-00000000a604' and module_id='7d385a26-27b2-4d14-807b-8d2a9c16cbf1';

-- a601 AI Agents: Tools, Not Members -> M2 (D2)
update public.lessons set
  module_id='a1111111-0000-0000-0000-000000000002',
  order_index=(select coalesce(max(order_index),0)+1 from public.lessons where module_id='a1111111-0000-0000-0000-000000000002')
where lesson_group_id='c0000000-0000-0000-0000-00000000a601' and module_id='7d385a26-27b2-4d14-807b-8d2a9c16cbf1';

-- a605 What to Delegate, What to Keep -> M2 (D2)
update public.lessons set
  module_id='a1111111-0000-0000-0000-000000000002',
  order_index=(select coalesce(max(order_index),0)+1 from public.lessons where module_id='a1111111-0000-0000-0000-000000000002')
where lesson_group_id='c0000000-0000-0000-0000-00000000a605' and module_id='7d385a26-27b2-4d14-807b-8d2a9c16cbf1';

-- a602 Done Means Done: DoD and AI Work -> M4 (D4)
update public.lessons set
  module_id='a1111111-0000-0000-0000-000000000004',
  order_index=(select coalesce(max(order_index),0)+1 from public.lessons where module_id='a1111111-0000-0000-0000-000000000004')
where lesson_group_id='c0000000-0000-0000-0000-00000000a602' and module_id='7d385a26-27b2-4d14-807b-8d2a9c16cbf1';

-- a603 New Impediments in AI-Augmented Teams -> M5 (D5)
update public.lessons set
  module_id='a1111111-0000-0000-0000-000000000005',
  order_index=(select coalesce(max(order_index),0)+1 from public.lessons where module_id='a1111111-0000-0000-0000-000000000005')
where lesson_group_id='c0000000-0000-0000-0000-00000000a603' and module_id='7d385a26-27b2-4d14-807b-8d2a9c16cbf1';

-- a606 Coaching the AI-Augmented Team -> M5 (D5)
update public.lessons set
  module_id='a1111111-0000-0000-0000-000000000005',
  order_index=(select coalesce(max(order_index),0)+1 from public.lessons where module_id='a1111111-0000-0000-0000-000000000005')
where lesson_group_id='c0000000-0000-0000-0000-00000000a606' and module_id='7d385a26-27b2-4d14-807b-8d2a9c16cbf1';

-- ---------------------------------------------------------------------------
-- (1c) Retire the now-empty D6 domain + Module 6 (guarded: only if empty).
-- ---------------------------------------------------------------------------

delete from public.modules m
where m.id='7d385a26-27b2-4d14-807b-8d2a9c16cbf1'
  and not exists (select 1 from public.lessons l where l.module_id = m.id);

delete from public.domains d
where d.certification_id='11111111-1111-1111-1111-111111111111' and d.code='D6'
  and not exists (select 1 from public.tasks t where t.domain_id = d.id);

-- ---------------------------------------------------------------------------
-- (2) Secure firewall cleanup: drop question_concepts for SM-I secure questions.
--     Scoped to pool='secure' so practice links are never touched.
-- ---------------------------------------------------------------------------

delete from public.question_concepts qc
where qc.question_id in (
  select q.id
  from public.quiz_questions q
  join public.tasks t on t.id = q.task_id
  join public.domains d on d.id = t.domain_id
  where d.certification_id = '11111111-1111-1111-1111-111111111111'
    and q.pool = 'secure'
);

-- ---------------------------------------------------------------------------
-- Verify after running (expected):
--   domains: 5 (D1-D5, no D6)
--   modules: 5 (no AI-Augmented Teams)
--   exam-scope per domain: D1 7/7, D2 11/11, D3 11/11, D4 11/11, D5 11/10
--   secure question_concepts links: 0   practice links: 3629 (untouched)
-- ---------------------------------------------------------------------------
