-- ============================================================================
-- 269_record_vendor_scrub_and_task_edits.sql
--
-- A RECORD of the vendor-name scrub, which DID leave files.
--
-- ---------------------------------------------------------------------------
-- *** CORRECTED 2026-09-01, AFTER THE FULL SCHEMA AUDIT. ***
--
-- AS FIRST COMMITTED, THIS FILE CLAIMED A THIRD UNDOCUMENTED LIVE CHANGE.
-- THERE IS NO THIRD. Subject 2 below has been rewritten; this block records
-- what the file used to say and why it was wrong, because a correction that
-- erases its own cause teaches nothing.
--
-- The original claimed tasks 4.9 and 5.7 on cert 11111111-... had been edited
-- with no migration behind them. BOTH ARE FULLY DOCUMENTED. The chain is
-- 003 -> 015 -> 091 and every link has a file.
--
-- HOW THE WRONG CLAIM GOT IN: 015 was read from line 35 onward -- where the
-- tasks.knowledge and concepts.description updates are -- and the lines above
-- were inferred rather than read. Lines 24 to 33 of 015 update BOTH task
-- statements, which is precisely what the claim said did not exist.
--
-- A MIGRATION WHOSE PURPOSE IS TO BE A RECORD IS THE WORST PLACE FOR AN
-- INFERENCE STATED AS A MEASUREMENT. The original wording was worse than
-- merely wrong: it said "read it and see", inviting the reader to verify
-- against the file that disproves it. Confidence was borrowed from a check
-- that had not been run.
--
-- WHAT THE AUDIT ACTUALLY FOUND, and the gap is SMALLER than this file feared,
-- not larger. Across nine object classes -- tables, views, functions,
-- triggers, policies, constraints, indexes, enum types and grants -- the
-- undocumented set was 26 tables, 2 functions, 1 trigger, 0 views and ZERO
-- unexplained content drift on cert 11111111-... Every one of that cert's 86
-- seeded concepts matches live exactly, and all six task statements that
-- differ from 003 are accounted for by 091's Bloom pass.
--
-- SO THE COUNT IS TWO, NOT THREE:
--
--   1. certifications.is_published was DROPPED with no migration file.
--      Recorded 2026-09-01 by migration 268. Known only from prose inside
--      three unrelated seed migrations, one of which exists because a
--      scaffold FAILED on the missing column.
--
--   2. on_profile_created_claim_vouchers -- the voucher-claim trigger on
--      public.profiles -- existed only in the live database. Migration 237
--      does `create or replace function` with no `create trigger`. CAPTURED
--      by 274. Its sibling on_auth_user_created on auth.users is still open.
--
-- Both are now closed or recorded: 268, 270 through 274.
--
-- The observation the original block reached for still holds, and is worth
-- keeping in the smaller form the evidence supports: a change is made in the
-- SQL editor, the result is correct, and the file that would have recorded it
-- is never written. The editor-first workflow is not the problem; it is
-- deliberate and it works. THE GAP IS BETWEEN "IT RAN" AND "IT WAS WRITTEN
-- DOWN", and nothing currently closes it except memory.
--
-- What is NOT supported is the leap from two instances to a pattern. Two is
-- two. This file made that leap and then supplied its own third instance by
-- getting one wrong, which is the more instructive failure.
--
-- ---------------------------------------------------------------------------
-- SUBJECT 1: THE VENDOR-NAME SCRUB.
--
-- A competitor's name was removed from learner-facing and structural content
-- by two migrations, both forward-only:
--
--   015_scrub_vendor_references.sql   *** DELETED 2026-09-01 ***
--       tasks.statement (4.9 and 5.7), tasks.knowledge (5.7) and three
--       concepts.description rows, all on cert 11111111-... Surgical phrase
--       swaps, not deletions. IT HAD ALREADY RUN; deleting the file changes
--       nothing in the database. ITS FULL BEFORE/AFTER MAPPING IS RECORDED
--       BELOW so that 003's current strings remain verifiable without it.
--
--   016_scrub_vendor_references_lessons.sql   RETAINED
--       lessons.content_md and one lessons.title, in ALL THREE LANGUAGES --
--       en, es-419, pt-BR -- as three separate localized statements.
--
--       016 IS KEPT AND THE REASON IS MECHANICAL, NOT SENTIMENTAL. Its
--       replacement strings contain 45 non-ASCII characters -- accented
--       Spanish and Portuguese -- and this file is ASCII-only per
--       CERT-SCHEMA-GUIDE section 8. The localized mapping CANNOT be moved
--       here without accent-stripping it, which would record strings that
--       never existed and match nothing. That is the mojibake failure
--       CLAUDE.md warns about, manufactured on purpose.
--
--       It also costs nothing to keep: 016 touches `lessons`, which 003 does
--       not seed. Nothing in 003 depends on it.
--
--       Note 016 also replaces references to Scrum.org. That is a different
--       body from the vendor masked here, it is cited deliberately by
--       TERMINOLOGY-POLICY.md rule 6 as a translation authority, and it is
--       left NAMED in 016 rather than masked.
--
-- VERIFIED CLEAN 2026-09-01. Zero rows across six columns:
--
--   tasks.statement            0
--   tasks.knowledge            0
--   concepts.name              0
--   concepts.description       0
--   lessons.content_md         0
--   lessons.title              0
--   certifications.provider    0
--
-- (Seven columns listed; provider is the seventh and was checked because
-- migration 135 records that it once defaulted to the vendor's name.)
--
-- A SCRUB THAT CANNOT SAY WHAT IT SCRUBBED IS NOT AUDITABLE. CLAIMS-POLICY.md
-- section 3.2 states this as a rule, and the mapping below is what discharges
-- it now that 015 is gone.
--
-- Every content correction made to 003_jta_curriculum.sql alongside this file
-- was derived from that mapping and from the live rows. Without it, the claim
-- "the file now matches the database" has no source to check against.
--
-- ---------------------------------------------------------------------------
-- THE 015 MAPPING, RECORDED IN FULL. <vendor> is the masked competitor name.
--
-- All on cert 11111111-1111-1111-1111-111111111111 (SM-AI-I).
--
-- tasks.statement -- two rows, WHOLE-VALUE assignment, not phrase swaps:
--
--   4.9  from  'Interpret burndown charts and velocity metrics (<vendor> emphasis)'
--        to    'Interpret burndown charts and velocity metrics'
--        (the parenthetical was dropped entirely)
--
--   5.7  from  'Navigate <vendor> vs. Scrum Guide terminology drift'
--        to    'Navigate terminology drift between legacy training materials
--               and the Scrum Guide'
--        LATER SUPERSEDED by 091:168 -- see SUBJECT 2. The live value today is
--        091's, not this one. Recorded anyway: without it the chain from 003
--        to live has a hole in the middle.
--
-- tasks.knowledge -- one row, surgical phrase swap preserving the rest:
--
--   5.7  '<vendor> prep materials'  ->  'legacy training materials'
--        guarded by  knowledge like '%<vendor> prep materials%'
--
-- concepts.description -- three rows, surgical phrase swaps:
--
--   '<vendor> sometimes uses'     ->  'Some training materials use'
--        guarded by  description like '<vendor> sometimes uses%'
--   '<vendor> materials may use'  ->  'some legacy materials may use'
--        guarded by  description like '%<vendor> materials may use%'
--   'and <vendor> materials'      ->  'and legacy training materials'
--        guarded by  description like '%and <vendor> materials%'
--
-- Those three land on the concepts servant-vs-true-leader,
-- ceremonies-vs-events-terminology and self-organizing-vs-self-managing.
-- All three were verified byte-identical between 003 and live on 2026-09-01,
-- along with the other 83 concepts 003 seeds.
--
-- THE LESSON MAPPING IS NOT REPRODUCED HERE. It is in 016, which is retained
-- for exactly that reason -- see above.
--
-- ---------------------------------------------------------------------------
-- SUBJECT 2: THE TWO TASK STATEMENTS, AND THE CHAIN IS COMPLETE.
--
-- Cert 11111111-1111-1111-1111-111111111111 (SM-AI-I). Tasks 4.9 and 5.7
-- differ from what 003 inserted. EVERY STEP HAS A FILE:
--
--   003 -> 015 (vendor scrub) -> 091 (Bloom pass)
--
-- TASK 4.9 -- 015:24-28, the vendor phrase DELETED, not replaced:
--   003 inserted : 'Interpret burndown charts and velocity metrics (<vendor> emphasis)'
--   015 set      : 'Interpret burndown charts and velocity metrics'
--   live today   : unchanged since. 091 did not touch 4.9.
--
-- TASK 5.7 -- changed TWICE, by 015 and then by 091:
--   003 inserted : 'Navigate <vendor> vs. Scrum Guide terminology drift'
--   015:30-34    : 'Navigate terminology drift between legacy training
--                   materials and the Scrum Guide'
--   091:168      : 'Translate between legacy training terminology and the
--                   2020 Scrum Guide'
--   live today   : the 091 value.
--
-- 091 IS WHY THE SECOND REWRITE HAPPENED, and it recorded its own reasoning in
-- the row. Its notes append reads: 'v2.0: statement verb was "Navigate" (an
-- Apply verb) while the skills said "Translate between the two" and the level
-- was 2_understand. Level kept; statement corrected.'
--
-- 5.7's KNOWLEDGE was changed by 015 in the same pass and is likewise
-- accounted for:
--   live today   : 'Where legacy training materials use legacy terms
--                   ("ceremonies," "self-organizing," "servant-leader")'
--
-- 091 rewrote FIVE other statements on this cert in the same Bloom pass --
-- 1.2, 3.3, 3.6, 3.9, 4.4 and 5.9 -- for the systematic defect it names in
-- its own header: SM-AI-I over-declared Analyze. Those five are not vendor
-- related and were never in question; they are listed here so a future reader
-- comparing 003 against live finds all six differences explained in one place.
--
-- Both live values were read from the database on 2026-09-01 and 003 has been
-- corrected to match them exactly, so the file and the row now agree.
--
-- NOTHING IS RE-APPLIED HERE. The live values are correct and this file does
-- not touch them. Re-running a replace against rows that already hold the
-- target text would be a no-op that looks like verification and is not.
--
-- ---------------------------------------------------------------------------
-- THIS FILE IS A RECORD, NOT A REBUILD STEP.
--
-- It contains no executable statement at all -- not even a guarded one --
-- because there is nothing to make idempotent: the scrub ran, the statements
-- were edited, and both results are already in the database.
--
-- Migration replay from zero has never worked in this repository and 269 does
-- not change that. See 268 for the same note at more length.
--
-- ---------------------------------------------------------------------------
-- VERIFICATION, run separately. Property, and both directions.
--
-- select 'tasks.statement'    as col, count(*) as n from public.tasks
--   where statement ilike '%<vendor>%'
-- union all select 'tasks.knowledge',      count(*) from public.tasks
--   where knowledge::text ilike '%<vendor>%'
-- union all select 'concepts.name',        count(*) from public.concepts
--   where name ilike '%<vendor>%'
-- union all select 'concepts.description', count(*) from public.concepts
--   where description ilike '%<vendor>%'
-- union all select 'lessons.content_md',   count(*) from public.lessons
--   where content_md ilike '%<vendor>%'
-- union all select 'lessons.title',        count(*) from public.lessons
--   where title ilike '%<vendor>%'
-- union all select 'certifications.provider', count(*) from public.certifications
--   where provider ilike '%<vendor>%';
--
-- Expect zero on every row. Substitute the vendor name, which is not written
-- in this file. IT IS STILL IN THE WORKING TREE: docs/BOK-ISMS-F.md and
-- BOK-AIMS-F.md name it a dozen times in sourced competitive analysis, kept
-- deliberately under CLAIMS-POLICY.md section 3.2 -- naming another
-- certification body is permitted in analysis, and removing those citations
-- would make the comparisons unverifiable rather than making them safer.
--
-- (This note used to say "substitute the name from 015's header, and that is
-- why 015 must not be deleted". 015 was deleted on 2026-09-01 once its full
-- mapping was recorded above. The instruction outlived its premise by one
-- commit, which is the failure mode this whole file is about.)
--
-- The POSITIVE half, which the zeroes alone do not prove:
--
-- select code, statement from public.tasks
--  where certification_id = '11111111-1111-1111-1111-111111111111'
--    and code in ('4.9','5.7') order by code;
--
-- Expect exactly the two statements quoted under SUBJECT 2. Seven zeroes are
-- also what an empty table returns.
-- ============================================================================
